### PR TITLE
`ekyna/payum-payzen-bundle` dependency and add test Application

### LINKED ISSUE #1: Compatibility with Sylius v1.8.x - Gateway not added to dropdown
Hello guys,

First of all, thanks for your Payzen bundle. 
I've a needs to use Payzen but I'm not able to create the payment after installing it on a Sylius 1.8.9.
The payment gateway does not appear in the dropdown.

I didn't check in the code what's wrong, but I'll if needed : 
- Bundle class not registered automatically in bundles.php
- In your docs :     Kiboko\Bundle\SyliusPayzenBundle\KibokoSyliusPayzenBundle::class => ['all' => true]
- But need to be :     Kiboko\SyliusPayzenBundle\KibokoSyliusPayzenBundle::class => ['all' => true]
- But still not detected by Sylius giving this error : Attempted to load class "KibokoSyliusPayzenBundle" from namespace "Kiboko\SyliusPayzenBundle". Did you forget a "use" statement for another namespace?

Do you use it on Sylius 1.8.X ?

### PR DESCRIPTION
**Pull request by Prometee**
Hello !

@gplanchat here is a PR following what we talk about on Slack : Sylius Developers.

I add a dependency to `ekyna/payum-payzen-bundle` and remove all unnecessary files from the repository as well as fixing some translations.
I also add a test Application to be able to test this plugin in the real world and also to run BeHat tests one day if someone will take care of it.

Tell me what do you think of it, and try to test it by executing those command lines :

> ⚠️⚠️⚠️ first create the file `tests/Application/.env.local` by copying `tests/Application/.env` and replace the value of `DATABASE_URL` ⚠️⚠️⚠️

```bash
composer install --no-interaction

(cd tests/Application \
  && yarn install\
  && bin/console doctrine:database:drop --if-exists --force -vvv\
  && bin/console doctrine:database:create -vvv\
  && bin/console doctrine:migrations:migrate -n -vvv -q\
  && bin/console assets:install public -vvv\
  && yarn build\
  && bin/console cache:warmup -vvv\
  && bin/console sylius:fixtures:load -n)

APP_ENV=dev symfony serve --port=8080 --dir=public
```

### CODE REVIEW

**Review by gplanchat — APPROVED** [review]

**Comment by tmarly** [comment]
Great job, Francis & Greg !

I tested it (on Sylius 1.10 & 1.11), I had to make a small change to make it work (otherwise I had an error, vads_amount missing):

```patch
diff --git a/src/Action/ConvertPaymentAction.php b/src/Action/ConvertPaymentAction.php
index 0e5c130..5f5fe54 100755
--- a/src/Action/ConvertPaymentAction.php
+++ b/src/Action/ConvertPaymentAction.php
@@ -49,7 +49,7 @@ class ConvertPaymentAction implements ActionInterface, GatewayAwareInterface

         $model = ArrayObject::ensureArrayObject($payment->getDetails());

-        if (false === $model['vads_amount']) {
+        if (false === ($model['vads_amount'] ?? false)) {
             $this->gateway->execute($currency = new GetCurrency($payment->getCurrencyCode()));
             if (2 < $currency->exp) {
                 throw new RuntimeException('Unexpected currency exp.');
```

And it worked perfectly :) (I tried success & failure. I did not try the autoresponse from the payzen server, my env is currently blocking remote IPs)

However I had a problem with these scenarios:
- I first choose another payment method (ex: bank transfer), then, from orders history, I tried to pay my order with payzen => critical (The option "status" does not exist)
- I choose payzen payment method, and I entered a wrong card number. Then, from orders history, I tried to my again my order with payzen => nothing happened (redirect to the same page).

(to be sure it was not related to my sylius store, I double checked on a brand new sylius install)

**Comment by Prometee** [comment]
@tmarly thanks for testing it with real credentials.

The issues you mentioned are common with Sylius and have to be fixed by each Sylius Payum plugins by making either Payum extension or prepend the `StatusAction` to search for the availability of the `status` and maybe one or more other specific Payzen fields.

Those issues can be addressed into another PR, WDYT ?

**Comment by Prometee** [comment]
@tmarly are you able to give me some response data examples from Payzen ? I should be able to write some tests with those data.

**Comment by tmarly** [comment]
> However I had a problem with these scenarios:
> 
> * I first choose another payment method (ex: bank transfer), then, from orders history, I tried to pay my order with payzen => critical (The option "status" does not exist)
> * I choose payzen payment method, and I entered a wrong card number. Then, from orders history, I tried to my again my order with payzen => nothing happened (redirect to the same page).

To fix these problems, I had to add these lines:

```diff
diff --git a/src/Action/ConvertPaymentAction.php b/src/Action/ConvertPaymentAction.php
index 354d1d7..9a7cc08 100755
--- a/src/Action/ConvertPaymentAction.php
+++ b/src/Action/ConvertPaymentAction.php
@@ -64,6 +64,14 @@ class ConvertPaymentAction implements ActionInterface, GatewayAwareInterface
             $model['vads_cust_email'] = $customer->getEmail();
         }
 
+        if (isset($model['status'])) {
+            // Status is set by Sylius after a first payment attempt.
+            // So if status is set, that means we are currently retrying, so we have to reset payzen parameters
+            unset($model['status']);
+            unset($model['vads_trans_id']);
+            unset($model['vads_trans_date']);
+        }
+
         $request->setResult((array)$model);
     }
```

Not sure this is the best approach, but it works for me. However I think that if I had another payment method (paypal, ...), it would not work (1st payment attempt with paypal, then 2nd with payzen, it may not work ?), the best would be to reset / unset all parameters except the ones required by PayZen.

**Comment by Prometee** [comment]
The issue is created by the fact that the field `details` of the `Payment` entity is filled with data from the previous gateway, to fix this a Payum Extension can be created to avoid this issue : on `onPreExecute` of `ConvertPaymentAction` and detect if one field name (or more) starting with `vads_` is present, if not then reset the `details` to `[]`.

**Comment by Prometee** [comment]
@tmarly Doing it inside an extension allows to separate each tasks, here we are targeting a specific issue and we don't need it inside the `ConvertPaymentAction`, this action is doing one thing and not multiple.
My last commit : https://github.com/kiboko-labs/payzen-bundle/pull/2/commits/7bb97f69ee505e75ea4a1aa034c9bf5cd630487a is solving this issue.

**Comment by tmarly** [comment]
heyyy nice trick @Prometee ! And I tried it, it works !
Thanks :)

**Pull request merged**
